
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
// import { usePathname } from "next/navigation";
import SidebarWrapper from "@/components/sideBarWraper/SidebarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Customer and Employee Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  //  const pathname = usePathname();
  // const hideSidebarRoutes = ['/login', '/register'];
  // const showSidebar = !hideSidebarRoutes.includes(pathname);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} app-container`}>
        <SidebarWrapper>
          {children}
        </SidebarWrapper>
        
      </body>
    </html>
  );
}
